version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Berlin
    ports:
      - "1880:1880"

    volumes:
      - node-red-data:/data

volumes:
  node-red-data: